### ISSUE TITLE
Interest Selection

### ISSUE THREAD

**Issue by banlon-jones** [padi-corextreme/padi-user-portal-backend#7]
Provide users with the option to choose their interests from a list including
categories such as clothing, home appliances, fashion, etc.

**Comment by mrkabby** [comment]
Please confirm if that's the list on  the page Interest Options 
I have attached a screenshot 
![Screenshot 2024-04-18 120604](https://github.com/padi-corextreme/padi-user-portal-backend/assets/159792882/48972672-6754-4070-b16f-a4c705f5fb8e)

**Comment by banlon-jones** [comment]
this is Ok
